# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, TAG images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master
  - david.docker

pool:
  vmImage: "Ubuntu-16.04"

variables:
  # from pipeline config: MONGODB_URI: "$(MONGODB_URI)"
  # from pipeline config: Docker.registry: "$(Docker.registry)"
  Docker.server: "$(Docker.registry).azurecr.io"
  Docker.image: "$(Docker.server)/ai2ai/ux:$(Build.BuildNumber)"

steps:
  - script: |
      cd ai-ui
      echo -n "MONGODB_URI=$(MONGODB_URI)" > ".env"
      yarn install --ignore-scripts --no-optional --frozen-lockfile
      yarn build:final
    displayName: "build app"

  -
   task: Docker@1
   displayName: Build image
   inputs: 
      command: build
      addDefaultLabels: true
      azureContainerRegistry: $(Docker.server)
      azureSubscriptionEndpoint: "arm-connection-rg-acr"
      context: $(System.DefaultWorkingDirectory)/ai-ui
      defaultContext: false
      dockerFile: ai-ui/Dockerfile
      imageName: $(Docker.image)
      includeLatestTag: false
      includeSourceTags: true
      qualifyImageName: true
      workingDirectory: $(System.DefaultWorkingDirectory)/ai-ui

  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      azureSubscriptionEndpoint: "arm-connection-rg-acr"
      azureContainerRegistry: $(Docker.server)
      imageName: $(Docker.image)
      qualifyImageName: true

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "build-final"
      targetPath: "ai-ui/build-final"

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "pipelines"
      targetPath: "pipelines"
